### ISSUE TITLE
MD5 encryption error

### ISSUE THREAD

**Issue by Russ93** [eibbors/mws-js#14]
I really love this library it is amazing and has helped me basically do everything with amazon I keep getting this error

Help would be much apreciated

```
{
    "ErrorResponse": {
        "$": {
            "xmlns": "http://mws.amazonaws.com/doc/2009-01-01/"
        },
        "Error": [
            {
                "Type": [
                    "Sender"
                ],
                "Code": [
                    "ContentMD5DoesNotMatch"
                ],
                "Message": [
                    "the Content-MD5 HTTP header you passed for your feed did not match the Content-MD5 we calculated for your feed"
                ],
                "Detail": [
                    ""
                ]
            }
        ],
        "RequestID": [
            "f996f554-5b80-407e-a66a-1fd701baa3c3"
        ]
    }
}
```

**Comment by ondreian** [comment]
Did you update your node.js environment?

**Comment by Russ93** [comment]
Yes and I found out what the issue was. The problem was there were weird characters in there that upon decryption on Amazons side the md5 hash wouldn't match

**Comment by patrickschaper** [comment]
When uploading product information with e.g. umlaut characters this error occures.
Using an html encoding library (https://github.com/mathiasbynens/he) helped but amazon doesn't decode afterwards.
Changing HTTPSRequest enconding didn't change anything either.

**Comment by sparkyfen** [comment]
Also, looks like crypto is misspelt in the code:

https://github.com/eibbors/mws-js/blob/95df778bf56f0730e311ecfa44db96e27d395cc0/lib/mws.js#L78

cryto should be crypto.

**Comment by sparkyfen** [comment]
This is still an issue with the spelling :)

**Comment by Russ93** [comment]
True but i found out that the issue with the encryption was that the user was putting non ascii characters in the data and it was causing a deflation problem when the data would be encrypted on amazons side
