### ISSUE TITLE
Request Signature Not Matching

### ISSUE THREAD

**Issue by ondreian** [eibbors/mws-js#8]
Sometime early this week anything that talks to MWS using this module began getting the dreaded error:

The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

No code has changed, so perhaps something with signing protocol changed for Amazon MWS that is rendering the signing method antiqued?

**Comment by danfinlay** [comment]
That's awful, it took me so long to find a module that did the signature right.  Amazon has the most complicated one I've ever seen.  I just started a new job and am overloaded, but good luck getting this addressed.

**Comment by ondreian** [comment]
This has to do with a change in some sort of underlying node.js thing, not Amazon.

When it iterates over the query keys, it doesn't just scan the object keys like it was before, but also methods and functions on the prototype chain.

```
// Copy query keys, sort them, then copy over the values
    for(var key in query)
      keys.push(key);
    keys = keys.sort();
    for(n in keys) {
      var key = keys[n];
      if(key != 'undefined' && typeof key != 'function') // add this to fix the problem
        sorted[key] = query[key];
    }
```

If you perform a typeof check and an undefined check on the key it will fix it appending a javascript function as a string to the AWS signature.
